title: My little site
author: Juaraca
email: naujzarimar16@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  What are you up to? In my blog you will see all my progress 
  and I will teach you all my skills about GitHub Pages
theme: jekyll-theme-merlot

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

